In [40]:
import numpy as np

In [41]:
benimDizim = np.random.randint(0, 15, 10)

In [42]:
benimDizim

array([ 0,  0,  7,  7,  3, 12, 13,  8, 12,  8])

In [43]:
benimDizim[9]

8

In [44]:
benimDizim[3:6]

array([ 7,  3, 12])

In [45]:
benimDizim[3:6] = -1

In [46]:
benimDizim

array([ 0,  0,  7, -1, -1, -1, 13,  8, 12,  8])

In [47]:
yeniDizi = np.random.randint(1, 10, 10)

In [48]:
yeniDizi

array([4, 8, 1, 5, 4, 7, 7, 5, 1, 1])

In [49]:
slicingDizisi = yeniDizi[3:8]

In [50]:
slicingDizisi

array([5, 4, 7, 7, 5])

In [51]:
slicingDizisi[:]

array([5, 4, 7, 7, 5])

In [52]:
slicingDizisi[:] = 0

In [53]:
slicingDizisi

array([0, 0, 0, 0, 0])

In [54]:
yeniDizi ##yeniDizinin içinden slicing ile aldığımız kısmı değiştirince yeniDizide aldığımız kısımda değişti

array([4, 8, 1, 0, 0, 0, 0, 0, 1, 1])

In [55]:
örnekDizi = np.arange(0,10)

In [56]:
örnekDizi

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
örnekDiziCopy = örnekDizi.copy()

In [58]:
örnekDiziCopy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
örnekDiziCopySlicing = örnekDiziCopy[3:8]

In [60]:
örnekDiziCopySlicing[:] = -1

In [61]:
örnekDiziCopySlicing

array([-1, -1, -1, -1, -1])

In [62]:
örnekDiziCopy

array([ 0,  1,  2, -1, -1, -1, -1, -1,  8,  9])

In [63]:
örnekDizi

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## matrix

In [64]:
benimListem = [[10,20,30], [50,60,70], [80,90,40]]

In [70]:
benimListem

[[10, 20, 30], [50, 60, 70], [80, 90, 40]]

In [65]:
benimMatrixDizim = np.array(benimListem)

In [66]:
benimMatrixDizim

array([[10, 20, 30],
       [50, 60, 70],
       [80, 90, 40]])

In [67]:
benimMatrixDizim[0]

array([10, 20, 30])

In [68]:
benimMatrixDizim[0][2]

30

In [71]:
benimMatrixDizim[1][1]

60

In [72]:
benimMatrixDizim[:,2]

array([30, 70, 40])

In [73]:
benimMatrixDizim[1:,1]

array([60, 90])

In [77]:
benimMatrixDizim

array([[10, 20, 30],
       [50, 60, 70],
       [80, 90, 40]])

In [74]:
benimMatrixDizim[0,:]

array([10, 20, 30])

In [75]:
benimMatrixDizim[0,:]

array([10, 20, 30])

In [76]:
benimMatrixDizim[0,1:]

array([20, 30])

In [78]:
benimMatrixDizim[1,1:2]

array([60])

In [79]:
yeniListe = ([0,1,2,3], [4,5,6,7], [8,9,10,11], [12,13,14,15], [16,17,18,19])

In [81]:
yeniMatrix = np.array(yeniListe)

In [82]:
yeniMatrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [83]:
yeniMatrix[0]

array([0, 1, 2, 3])

In [85]:
yeniMatrix[[0,3,4]]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## operasyonlar

In [90]:
operasyonDizi = np.random.randint(1, 100, 20)

In [91]:
operasyonDizi

array([32,  5, 32, 26, 17, 55, 84, 83, 60, 58, 36, 27, 91, 92,  1, 40, 70,
       30, 14, 29])

In [92]:
operasyonDizi > 50

array([False, False, False, False, False,  True,  True,  True,  True,
        True, False, False,  True,  True, False, False,  True, False,
       False, False])

In [96]:
sonucDizisi = operasyonDizi > 50

In [97]:
sonucDizisi

array([False, False, False, False, False,  True,  True,  True,  True,
        True, False, False,  True,  True, False, False,  True, False,
       False, False])

In [98]:
operasyonDizi[sonucDizisi]

array([55, 84, 83, 60, 58, 91, 92, 70])

In [100]:
operasyonDizi[operasyonDizi > 50]

array([55, 84, 83, 60, 58, 91, 92, 70])

In [95]:
tempList = []
for i in operasyonDizi:
    if i > 50:
        tempList.append(i)
print(tempList)

[55, 84, 83, 60, 58, 91, 92, 70]


In [101]:
sonDizi = np.arange(0,20)

In [102]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [105]:
sonDizi + sonDizi # aynı şey tüm operatörler için geçerli.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [106]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])