In [42]:
import numpy as np

In [43]:
a = np.array([1,2,3,4,5])

In [44]:
 matrixListesi = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [45]:
matrixListesi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# arange

In [46]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [47]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

#  zeros

In [49]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

#  linspace

In [50]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [51]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

#  eye

In [52]:
np.eye(3)#birim matris

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# random

In [53]:
np.random.rand(4)#standart dağılıma(normal dağılım)

array([0.21087808, 0.91060688, 0.33929656, 0.41607011])

In [54]:
np.random.rand(2,2)

array([[0.616125  , 0.59806523],
       [0.25961586, 0.92225394]])

In [55]:
np.random.randint(1,10)

3

In [77]:
a = np.random.randint(1,10,3)
a

array([3, 8, 3])

In [78]:
benimNumpyDizim = np.arange(30)

In [79]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [80]:
benimRandomDizim = np.random.randint(0,100,20)

In [81]:
benimRandomDizim

array([51, 34, 91,  4,  1, 74, 98, 62, 27,  4, 19, 57, 55, 64, 32, 78, 85,
       12, 88, 54])

# numpy dizi metotları

In [82]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [83]:
benimRandomDizim.reshape(5,4)

array([[51, 34, 91,  4],
       [ 1, 74, 98, 62],
       [27,  4, 19, 57],
       [55, 64, 32, 78],
       [85, 12, 88, 54]])

In [84]:
benimRandomDizim.max()

98

In [85]:
benimRandomDizim.argmax()

6

In [86]:
benimNumpyDizim.argmax()

29

In [87]:
benimRandomDizim.argmin()

4

In [88]:
benimNumpyDizim.ndim

1

In [89]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [90]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [91]:
reshapeDizim.ndim

2

In [92]:
reshapeDizim.shape

(5, 6)

In [93]:
benimNumpyDizim.shape

(30,)

In [96]:
a = rng.random((3,2))
a

NameError: name 'rng' is not defined

In [95]:
rng.integers(5, size=(2, 4))

NameError: name 'rng' is not defined

In [103]:
from numpy import pi
x = np.linspace(0, 2 * pi, 1)
f = np.sin(x)

In [104]:
f

array([0.])